### ISSUE TITLE
可以分享下论文附录么？

### ISSUE THREAD

**Issue by AmazingDD** [Zhangcx19/GPFedRec#2]

**Comment by Zhangcx19** [comment]
你好！非常感谢对我们工作的关注，论文正文及附录见https://dl.acm.org/doi/pdf/10.1145/3637528.3671702

**Comment by yudi-mars** [comment]
你好，您附上的链接我有查看，里面的补充材料只有一份视频，而我在您的论文里看到你们有在附录中讨论算法的收敛性，我对此表示十分好奇，请问可以提供相应的材料下载链接么？

**Comment by Zhangcx19** [comment]
你好，收敛性分析在上述链接中第11页，附录C，请查阅！

**Comment by yudi-mars** [comment]
好的 感谢
